image: registry.gitlab.com/kroesche/bmsnode

stages:
    - build
    - test
    - release

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    BUILD_DIR: "build"
    TEST_DIR: "test"
    DOC_DIR: "doc"
    DOC_BUILD_DIR: "doc/build"

cache:
    paths:
        - $PIP_CACHE_DIR
        - $BUILD_DIR/vertool
        - $BUILD_DIR/venv
        - $TEST_DIR/venv

devbuild:
    stage: build
    rules:
        - if: '$CI_COMMIT_TAG != null'
          when: never
        - if: '$CI_COMMIT_BRANCH != "master"'
          when: always
    script:
        - "make -C $BUILD_DIR clean"
        - "make -C $BUILD_DIR package"
    artifacts:
        paths:
            - "$BUILD_DIR/obj/bmsnode.*"
            - "$BUILD_DIR/bmsnode-*.tar.gz"
            - "$BUILD_DIR/buildlog.txt"

build:
    stage: build
    rules:
        - if: '$CI_COMMIT_TAG != null'
          when: never
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: always
    script:
        - "make -C $BUILD_DIR clean"
        - "make -C $BUILD_DIR package PRODUCTION=1"
    artifacts:
        paths:
            - "$BUILD_DIR/obj/bmsnode.*"
            - "$BUILD_DIR/bmsnode-*.tar.gz"
            - "$BUILD_DIR/buildlog.txt"

test:
    stage: test
    except:
        - tags
    script:
        - "make -C $BUILD_DIR cleantest"
        - "make -C $BUILD_DIR test"
    artifacts:
        when: always
        paths:
            - "$TEST_DIR/reports/*.html"
            - "$TEST_DIR/reports/check-badge.svg"
            - "$TEST_DIR/reports/check/*.html"
        reports:
            junit: "$TEST_DIR/reports/bmstest-junit.xml"

release:
    stage: release
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: manual
    script:
        - "make -C $BUILD_DIR ci-status"
        - "make -C $BUILD_DIR release PRODUCTION=1"

pages:
    stage: build
    script:
        - "make -C $DOC_BUILD_DIR clean"
        - "make -C $DOC_BUILD_DIR"
        - "mkdir -p public"
        - "cp -r doc/build/html/ public/html/"
        - "cp -r doc/build/firmware-docs.html public/."
    artifacts:
        paths:
            - public
            - "$DOC_BUILD_DIR/firmware-docs.html"
            - "$DOC_BUILD_DIR/html/"
