image: registry.gitlab.com/kroesche/bmsnode

stages:
    - build
    - test
    - release

variables:
    PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"
    BUILD_DIR: "build"
    TEST_DIR: "test"

cache:
    paths:
        - $PIP_CACHE_DIR
#    - $BUILD_DIR/vertool
#    - $BUILD_DIR/venv

build:
    stage: build
    rules:
        - if: '$CI_COMMIT_BRANCH != "master"'
          when: always
    script:
        - "make -C $BUILD_DIR clean"
        - "make -C $BUILD_DIR package"
    artifacts:
        paths:
            - "$BUILD_DIR/obj/bmsnode.*"
            - "doc/license-badge.svg"
            - "$BUILD_DIR/bmsnode-*.tar.gz"

buildprod:
    stage: build
    rules:
        - if: '$CI_COMMIT_BRANCH == "master"'
          when: always
    script:
        - "make -C $BUILD_DIR clean"
        - "make -C $BUILD_DIR package PRODUCTION=1"
    artifacts:
        paths:
            - "$BUILD_DIR/obj/bmsnode.*"
            - "doc/license-badge.svg"
            - "$BUILD_DIR/bmsnode-*.tar.gz"

test:
    stage: test
    except:
        - tags
    script:
        - "make -C $BUILD_DIR cleantest"
        - "make -C $BUILD_DIR test"
    artifacts:
        paths:
            - "$TEST_DIR/reports/*.html"
            - "$TEST_DIR/reports/check-badge.svg"
            - "$TEST_DIR/reports/check/*.html"
        reports:
            junit: "$TEST_DIR/reports/bmstest-junit.xml"
