/******************************************************************************
 *
 * MIT License
 *
 * Copyright (c) 2020 Joseph Kroesche
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 *****************************************************************************/

#include <stdint.h>

/**
 *
 * This file was generated by https://github.com/kroesche/thermistor_lookup
 *
 * Generated on 2020-04-07 13:29:04.200273
 * for a thermistor circuit with the following parameters:
 *
 * input file: v4proto.json
 * board: diyBMSv4 prototype (oshpark purple) board
 * thermistor: Sunlord SDNT2012X473F4150FTF
 *
 * Tstart=0 Tstop=80 Tstep=8
 * Tnominal=25 Rnominal=47000 Rpulldown=47000
 * beta=4150 counts=1023
 *
 */

static const uint16_t therm_table[] =
{
    223, // [ 0] C= 0 R=168248
    308, // [ 1] C= 8 R=109143
    402, // [ 2] C=16 R=72518
    500, // [ 3] C=24 R=49256
    593, // [ 4] C=32 R=34142
    676, // [ 5] C=40 R=24113
    747, // [ 6] C=48 R=17328
    806, // [ 7] C=56 R=12654
    853, // [ 8] C=64 R=9379
    890, // [ 9] C=72 R=7050
};

#define T_AT_IDX(idx) ((idx) * 8)
#define T_STEP (8)
#define T_LAST_IDX (9)

// Calculate temperature using lookup table.
// See header file for API description
int16_t adc_to_temp(uint16_t adc)
{
    uint16_t idx;
    int16_t adc0;
    int16_t adc1;
    int16_t temp0 = 0;

    if (adc < therm_table[0])
    {
        adc0 = therm_table[0];
        adc1 = therm_table[1];
        temp0 = T_AT_IDX(0);
    }
    else if (adc >= therm_table[T_LAST_IDX])
    {
        adc0 = therm_table[T_LAST_IDX - 1];
        adc1 = therm_table[T_LAST_IDX];
        temp0 = T_AT_IDX(T_LAST_IDX - 1);
    }

    else
    {
        for (idx = 0; idx < T_LAST_IDX; ++idx)
        {
            adc0 = therm_table[idx];
            adc1 = therm_table[idx + 1];
            if (adc < adc1)
            {
                temp0 = T_AT_IDX(idx);
                break;
            }
        }
    }

    int16_t delta = adc - adc0;
    int16_t range = adc1 - adc0;
    int16_t half_digit = range >> 1;

    int16_t temp = delta * T_STEP + half_digit;
    temp /= range;
    temp += temp0;

    return temp;
}
