/******************************************************************************
 * SPDX-License-Identifier: MIT
 *
 * Copyright (c) 2021 Joseph Kroesche
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 *****************************************************************************/

#include <stdint.h>

/** @addtogroup therm Thermistor
 *
 * This file was generated by https://github.com/kroesche/thermistor_lookup
 *
 * Generated on 2021-05-20 16:39:30.943049,<br/>
 * for a thermistor circuit with the following parameters:
 *
 * |Parameter |Value                         |
 * |----------|------------------------------|
 * |Input File|bmsnode3.json                 |
 * |Board     |BMSNode 3.0.0 board           |
 * |Thermistor|TDK NTCG163JF103FT1           |
 * |Tstart    |0                             |
 * |Tstop     |80                            |
 * |Tstep     |4                             |
 * |Tnominal  |25                            |
 * |Rnominal  |10000                         |
 * |Rpulldown |10000                         |
 * |beta      |3380                          |
 * |counts    |1023                          |
 *
 * @{
 */

static const uint16_t therm_table[] =
{
    267, // [ 0] C= 0 R=28255
    304, // [ 1] C= 4 R=23629
    343, // [ 2] C= 8 R=19861
    382, // [ 3] C=12 R=16776
    422, // [ 4] C=16 R=14236
    462, // [ 5] C=20 R=12136
    502, // [ 6] C=24 R=10389
    540, // [ 7] C=28 R=8931
    578, // [ 8] C=32 R=7708
    613, // [ 9] C=36 R=6678
    647, // [10] C=40 R=5807
    679, // [11] C=44 R=5067
    709, // [12] C=48 R=4437
    736, // [13] C=52 R=3897
    761, // [14] C=56 R=3434
    785, // [15] C=60 R=3036
    806, // [16] C=64 R=2691
    826, // [17] C=68 R=2392
    843, // [18] C=72 R=2133
    859, // [19] C=76 R=1906
};

#define T_AT_IDX(idx) ((idx) * 4)
#define T_STEP (4)
#define T_LAST_IDX (19)

// Calculate temperature using lookup table.
// See header file for API description
int16_t adc_to_temp(uint16_t adc)
{
    uint16_t idx;
    int16_t adc0;
    int16_t adc1;
    int16_t temp0 = 0; // prevent g++ warning

    if (adc < therm_table[0])
    {
        adc0 = therm_table[0];
        adc1 = therm_table[1];
        temp0 = T_AT_IDX(0);
    }
    else if (adc >= therm_table[T_LAST_IDX])
    {
        adc0 = therm_table[T_LAST_IDX - 1];
        adc1 = therm_table[T_LAST_IDX];
        temp0 = T_AT_IDX(T_LAST_IDX - 1);
    }

    else
    {
        for (idx = 0; idx < T_LAST_IDX; ++idx)
        {
            adc0 = therm_table[idx];
            adc1 = therm_table[idx + 1];
            if (adc < adc1)
            {
                temp0 = T_AT_IDX(idx);
                break;
            }
        }
    }

    int16_t delta = (int16_t)adc - adc0;
    int16_t range = adc1 - adc0;
    int16_t half_digit = range >> 1;

    int16_t temp = delta * T_STEP + half_digit;
    temp /= range;
    temp += temp0;

    return temp;
}
